-- =============================================================
-- 237Biz Growth Partner — Phase 3A Migration
-- Run AFTER growth-partner-p2-migration.sql (Phase 2)
-- Import via phpMyAdmin: select your database first, then Import.
-- =============================================================

SET FOREIGN_KEY_CHECKS=0;

-- ─────────────────────────────────────────────
-- 1. AI RECOMMENDATIONS
--    Rule-based recommendations generated by the system.
--    Each recommendation identifies a problem/opportunity
--    and provides a direct action for the partner.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_recommendations (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_id      INT UNSIGNED NOT NULL,
    listing_id      INT UNSIGNED,                 -- null = portfolio-wide
    rule_key        VARCHAR(80) NOT NULL,          -- e.g. 'no_review_activity'
    title           VARCHAR(200) NOT NULL,
    description     TEXT NOT NULL,
    priority        ENUM('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
    recommended_action VARCHAR(200),              -- human-readable action label
    action_type     VARCHAR(80),                  -- 'create_campaign','open_lead', etc.
    action_url      VARCHAR(500),                 -- pre-built URL for one-click action
    action_data     JSON,                         -- extra params for the action
    objective       VARCHAR(200),
    status          ENUM('new','viewed','actioned','dismissed','expired')
                        NOT NULL DEFAULT 'new',
    expires_at      TIMESTAMP NULL,               -- auto-expire stale recommendations
    actioned_at     TIMESTAMP NULL,
    dismissed_at    TIMESTAMP NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_rec_partner  (partner_id),
    KEY idx_rec_listing  (listing_id),
    KEY idx_rec_status   (partner_id, status),
    KEY idx_rec_rule     (partner_id, rule_key, listing_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────
-- 2. GROWTH ALERTS
--    Intelligent alerts: positive, opportunity, attention, urgent.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS growth_alerts (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_id      INT UNSIGNED NOT NULL,
    listing_id      INT UNSIGNED,                 -- null = portfolio-wide
    alert_type      VARCHAR(80) NOT NULL,         -- e.g. 'profile_views_up','overdue_leads'
    priority        ENUM('informational','opportunity','attention','urgent')
                        NOT NULL DEFAULT 'attention',
    title           VARCHAR(200) NOT NULL,
    body            TEXT NOT NULL,
    action_label    VARCHAR(100),
    action_url      VARCHAR(500),
    status          ENUM('new','viewed','actioned','dismissed') NOT NULL DEFAULT 'new',
    expires_at      TIMESTAMP NULL,
    actioned_at     TIMESTAMP NULL,
    dismissed_at    TIMESTAMP NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_alert_partner (partner_id),
    KEY idx_alert_listing (listing_id),
    KEY idx_alert_status  (partner_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────
-- 3. GROWTH SCORE HISTORY
--    Computed score stored each time it is calculated
--    so trends can be displayed over time.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS growth_score_history (
    id                   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    listing_id           INT UNSIGNED NOT NULL,
    partner_id           INT UNSIGNED NOT NULL,
    score                TINYINT UNSIGNED NOT NULL DEFAULT 0,  -- 0-100
    profile_score        TINYINT UNSIGNED NOT NULL DEFAULT 0,
    engagement_score     TINYINT UNSIGNED NOT NULL DEFAULT 0,
    lead_score           TINYINT UNSIGNED NOT NULL DEFAULT 0,
    review_score         TINYINT UNSIGNED NOT NULL DEFAULT 0,
    campaign_score       TINYINT UNSIGNED NOT NULL DEFAULT 0,
    content_score        TINYINT UNSIGNED NOT NULL DEFAULT 0,
    task_score           TINYINT UNSIGNED NOT NULL DEFAULT 0,
    score_breakdown      JSON,                    -- full component breakdown
    computed_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_gsh_listing  (listing_id),
    KEY idx_gsh_partner  (partner_id),
    KEY idx_gsh_date     (listing_id, computed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────
-- 4. AI CONVERSATIONS (stub — ready for API wiring)
--    Stores conversation history for the AI Growth Assistant.
--    Keyed by session so conversations can be resumed.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_conversations (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_id      INT UNSIGNED NOT NULL,
    listing_id      INT UNSIGNED,                 -- context: which business
    user_id         INT UNSIGNED NOT NULL,
    session_key     VARCHAR(64) NOT NULL,          -- groups messages into one conversation
    role            ENUM('user','assistant','system') NOT NULL,
    content         TEXT NOT NULL,
    token_count     INT UNSIGNED,
    model_used      VARCHAR(80),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_conv_session  (session_key),
    KEY idx_conv_partner  (partner_id, listing_id),
    KEY idx_conv_user     (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────
-- 5. AI GENERATED CONTENT (stub)
--    Tracks all AI-generated content, edits and approval status.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_generated_content (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_id      INT UNSIGNED NOT NULL,
    listing_id      INT UNSIGNED,
    user_id         INT UNSIGNED NOT NULL,
    content_type    VARCHAR(80) NOT NULL,          -- 'social_post','review_request', etc.
    platform        VARCHAR(50),
    style           VARCHAR(50),
    prompt_summary  VARCHAR(500),
    generated_text  TEXT NOT NULL,
    edited_text     TEXT,
    approval_status ENUM('pending','approved','rejected','auto_approved')
                        NOT NULL DEFAULT 'pending',
    approved_by     INT UNSIGNED,
    approved_at     TIMESTAMP NULL,
    model_used      VARCHAR(80),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_agc_partner (partner_id),
    KEY idx_agc_listing (listing_id),
    KEY idx_agc_status  (partner_id, approval_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────
-- 6. COMMUNICATION TEMPLATES
--    Reusable message templates with variable substitution.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS communication_templates (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_id      INT UNSIGNED NOT NULL,
    name            VARCHAR(200) NOT NULL,
    template_type   ENUM(
                        'welcome','lead_followup','appointment_reminder',
                        'review_request','promotion','re_engagement',
                        'thank_you','event_reminder','customer_followup',
                        'custom'
                    ) NOT NULL DEFAULT 'custom',
    channel         ENUM('email','whatsapp','sms','internal') NOT NULL DEFAULT 'email',
    subject         VARCHAR(300),                 -- email subject
    body            TEXT NOT NULL,                -- supports {name},{business}, etc.
    variables       JSON,                         -- list of variable names used
    status          ENUM('active','inactive') NOT NULL DEFAULT 'active',
    use_count       INT UNSIGNED NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_ct_partner (partner_id),
    KEY idx_ct_type    (partner_id, template_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────
-- 7. AUTOMATION WORKFLOWS (stub — Phase 3C)
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS automation_workflows (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_id      INT UNSIGNED NOT NULL,
    listing_id      INT UNSIGNED,                 -- null = applies to all portfolio
    name            VARCHAR(200) NOT NULL,
    description     TEXT,
    trigger_type    VARCHAR(80) NOT NULL,          -- 'new_lead','booking_completed', etc.
    trigger_config  JSON,
    execution_mode  ENUM('automatic','requires_approval','manual')
                        NOT NULL DEFAULT 'requires_approval',
    status          ENUM('active','paused','draft') NOT NULL DEFAULT 'draft',
    run_count       INT UNSIGNED NOT NULL DEFAULT 0,
    last_run_at     TIMESTAMP NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_aw_partner (partner_id),
    KEY idx_aw_trigger (trigger_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────
-- 8. AUTOMATION STEPS (WHEN→IF→THEN actions)
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS automation_steps (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workflow_id     INT UNSIGNED NOT NULL,
    step_order      TINYINT UNSIGNED NOT NULL DEFAULT 0,
    step_type       ENUM('condition','action','wait') NOT NULL DEFAULT 'action',
    action_type     VARCHAR(80),                  -- 'create_task','send_notification', etc.
    condition_field VARCHAR(80),
    condition_op    VARCHAR(20),                  -- 'equals','not_equals','greater_than'
    condition_value VARCHAR(200),
    wait_minutes    INT UNSIGNED,                 -- for wait steps
    config          JSON,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_as_workflow (workflow_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────
-- 9. AUTOMATION RUNS (execution log)
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS automation_runs (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workflow_id     INT UNSIGNED NOT NULL,
    partner_id      INT UNSIGNED NOT NULL,
    listing_id      INT UNSIGNED,
    trigger_ref_type VARCHAR(40),                 -- 'lead','booking','review'
    trigger_ref_id  INT UNSIGNED,
    status          ENUM('pending','running','completed','failed','cancelled','awaiting_approval')
                        NOT NULL DEFAULT 'pending',
    approval_required TINYINT(1) NOT NULL DEFAULT 0,
    approved_by     INT UNSIGNED,
    approved_at     TIMESTAMP NULL,
    started_at      TIMESTAMP NULL,
    completed_at    TIMESTAMP NULL,
    error_message   TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_ar_workflow (workflow_id),
    KEY idx_ar_partner  (partner_id),
    KEY idx_ar_status   (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────
-- 10. AI AUDIT TRAIL
--     All AI-generated actions are traceable.
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_audit_log (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_id      INT UNSIGNED NOT NULL,
    listing_id      INT UNSIGNED,
    user_id         INT UNSIGNED NOT NULL,
    action_type     VARCHAR(80) NOT NULL,          -- 'content_generated','recommendation_actioned'
    ref_type        VARCHAR(40),
    ref_id          INT UNSIGNED,
    prompt_summary  VARCHAR(500),
    generated_output TEXT,
    user_edits      TEXT,
    approval_status ENUM('pending','approved','rejected','auto') NOT NULL DEFAULT 'pending',
    approved_by     INT UNSIGNED,
    approved_at     TIMESTAMP NULL,
    final_version   TEXT,
    ip_address      VARCHAR(45),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_aal_partner (partner_id),
    KEY idx_aal_user    (user_id),
    KEY idx_aal_type    (action_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────
-- 11. REPORT SCHEDULES (automated reporting)
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS report_schedules (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_id      INT UNSIGNED NOT NULL,
    listing_id      INT UNSIGNED NOT NULL,
    frequency       ENUM('monthly','weekly','quarterly') NOT NULL DEFAULT 'monthly',
    day_of_month    TINYINT UNSIGNED NOT NULL DEFAULT 1,  -- 1-28
    auto_generate   TINYINT(1) NOT NULL DEFAULT 1,
    auto_share      TINYINT(1) NOT NULL DEFAULT 0,        -- requires approval by default
    notify_partner  TINYINT(1) NOT NULL DEFAULT 1,
    notify_owner    TINYINT(1) NOT NULL DEFAULT 0,
    status          ENUM('active','paused') NOT NULL DEFAULT 'active',
    last_run_at     TIMESTAMP NULL,
    next_run_at     TIMESTAMP NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_rs_partner (partner_id),
    KEY idx_rs_next    (status, next_run_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────
-- 12. REVIEW REQUESTS (review automation tracking)
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS review_requests (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_id      INT UNSIGNED NOT NULL,
    listing_id      INT UNSIGNED NOT NULL,
    campaign_id     INT UNSIGNED,
    customer_name   VARCHAR(200),
    customer_email  VARCHAR(200),
    customer_phone  VARCHAR(60),
    channel         ENUM('email','whatsapp','sms') NOT NULL DEFAULT 'email',
    status          ENUM('pending','sent','delivered','clicked','reviewed',
                         'failed','opted_out') NOT NULL DEFAULT 'pending',
    sent_at         TIMESTAMP NULL,
    delivered_at    TIMESTAMP NULL,
    clicked_at      TIMESTAMP NULL,
    reviewed_at     TIMESTAMP NULL,
    review_id       INT UNSIGNED,                 -- links to reviews table if review received
    reminder_sent   TINYINT(1) NOT NULL DEFAULT 0,
    reminder_at     TIMESTAMP NULL,
    opted_out_at    TIMESTAMP NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_rr_partner   (partner_id),
    KEY idx_rr_listing   (listing_id),
    KEY idx_rr_campaign  (campaign_id),
    KEY idx_rr_status    (listing_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
